from django.utils.translation import ugettext_lazy as _

US_STATES_TERR = (
    ('AL','Alabama'),
    ('AK','Alaska'),
    ('AZ','Arizona'),
    ('AR','Arkansas'),
    ('CA','California'),
    ('CO','Colorado'),
    ('CT','Connecticut'),
    ('DE','Delaware'),
    ('FL','Florida'),
    ('GA','Georgia'),
    ('HI','Hawaii'),
    ('ID','Idaho'),
    ('IL','Illinois'),
    ('IN','Indiana'),
    ('IA','Iowa'),
    ('KS','Kansas'),
    ('KY','Kentucky'),
    ('LA','Louisiana'),
    ('ME','Maine'),
    ('MD','Maryland'),
    ('MA','Massachusetts'),
    ('MI','Michigan'),
    ('MN','Minnesota'),
    ('MS','Mississippi'),
    ('MO','Missouri'),
    ('MT','Montana'),
    ('NE','Nebraska'),
    ('NV','Nevada'),
    ('NH','New Hampshire'),
    ('NJ','New Jersey'),
    ('NM','New Mexico'),
    ('NY','New York'),
    ('NC','North Carolina'),
    ('ND','North Dakota'),
    ('OH','Ohio'),
    ('OK','Oklahoma'),
    ('OR','Oregon'),
    ('PA','Pennsylvania'),
    ('RI','Rhode Island'),
    ('SC','South Carolina'),
    ('SD','South Dakota'),
    ('TN','Tennessee'),
    ('TX','Texas'),
    ('UT','Utah'),
    ('VT','Vermont'),
    ('VA','Virginia'),
    ('WA','Washington'),
    ('WV','West Virginia'),
    ('WI','Wisconsin'),
    ('WY','Wyoming'),
    ('AS','American Samoa'),
    ('DC','District of Columbia'),
    ('FM','Federated States of Micronesia'),
    ('GU','Guam'),
    ('MH','Marshall Islands'),
    ('MP','Northern Mariana Islands'),
    ('PW','Palau'),
    ('PR','Puerto Rico'),
    ('VI','Virgin Islands'),
)

GENDER_CHOICES = (
    (0, _('Male')),
    (1, _('Female'))
)

ORIGIN_COUNTRY_CHOICES = (
    ("US",_('UNITED STATES OF AMERICA')),
    ("AF",_('AFGHANISTAN')),
    ("AL",_('ALBANIA')),
    ("DZ",_('ALGERIA')),
    ("AS",_('AMERICAN SAMOA')),
    ("AD",_('ANDORRA')),
    ("AO",_('ANGOLA')),
    ("AI",_('ANGUILLA')),
    ("AQ",_('ANTARCTICA')),
    ("AG",_('ANTIGUA AND BARBUDA')),
    ("AR",_('ARGENTINA')),
    ("AM",_('ARMENIA')),
    ("AW",_('ARUBA')),
    ("AU",_('AUSTRALIA')),
    ("AT",_('AUSTRIA')),
    ("AZ",_('AZERBAIJAN')),
    ("BS",_('BAHAMAS')),
    ("BH",_('BAHRAIN')),
    ("BD",_('BANGLADESH')),
    ("BB",_('BARBADOS')),
    ("BY",_('BELARUS')),
    ("BE",_('BELGIUM')),
    ("BZ",_('BELIZE')),
    ("BJ",_('BENIN')),
    ("BM",_('BERMUDA')),
    ("BT",_('BHUTAN')),
    ("BO",_('BOLIVIA')),
    ("BQ",_('BONAIRE SINT EUSTATIUS AND SABA')),
    ("BA",_('BOSNIA HERCEGOVINA')),
    ("BW",_('BOTSWANA')),
    ("BV",_('BOUVET ISLAND')),
    ("BR",_('BRAZIL')),
    ("IO",_('BRITISH INDIAN OCEAN TERRITORY')),
    ("BN",_('BRUNEI DARUSSALAM')),
    ("BG",_('BULGARIA')),
    ("BF",_('BURKINA FASO')),
    ("BI",_('BURUNDI')),
    ("KH",_('CAMBODIA')),
    ("CM",_('CAMEROON')),
    ("CA",_('CANADA')),
    ("IC",_('CANARY ISLANDS')),
    ("CV",_('CAPE VERDE')),
    ("KY",_('CAYMAN ISLANDS')),
    ("CF",_('CENTRAL AFRICAN REPUBLIC')),
    ("EA",_('CEUTA AND MELILLA')),
    ("TD",_('CHAD')),
    ("CL",_('CHILE')),
    ("CN",_('CHINA')),
    ("CX",_('CHRISTMAS ISLAND')),
    ("CC",_('COCOS (KEELING) ISLANDS')),
    ("CO",_('COLOMBIA')),
    ("KM",_('COMOROS')),
    ("CG",_('CONGO')),
    ("CD",_('CONGO THE DEMOCRATIC REPUBLIC OF THE')),
    ("CK",_('COOK ISLANDS')),
    ("CR",_('COSTA RICA')),
    ("HR",_('CROATIA')),
    ("CW",_('CURACAO')),
    ("CY",_('CYPRUS')),
    ("CZ",_('CZECH REPUBLIC')),
    ("CI",_('COTE D''IVOIRE (IVORY COAST)')),
    ("DK",_('DENMARK')),
    ("DJ",_('DJIBOUTI')),
    ("DM",_('DOMINICA')),
    ("DO",_('DOMINICAN REPUBLIC')),
    ("EC",_('ECUADOR')),
    ("EG",_('EGYPT')),
    ("SV",_('EL SALVADOR')),
    ("GQ",_('EQUATORIAL GUINEA')),
    ("ER",_('ERITREA')),
    ("EE",_('ESTONIA')),
    ("ET",_('ETHIOPIA')),
    ("FK",_('FALKLAND ISLANDS')),
    ("FO",_('FAROE ISLANDS')),
    ("FJ",_('FIJI')),
    ("FI",_('FINLAND')),
    ("FR",_('FRANCE')),
    ("GF",_('FRENCH GUIANA')),
    ("PF",_('FRENCH POLYNESIA')),
    ("TF",_('FRENCH SOUTHERN TERRITORIES')),
    ("GA",_('GABON')),
    ("GM",_('GAMBIA')),
    ("GE",_('GEORGIA')),
    ("DE",_('GERMANY')),
    ("GH",_('GHANA')),
    ("GI",_('GIBRALTAR')),
    ("GR",_('GREECE')),
    ("GL",_('GREENLAND')),
    ("GD",_('GRENADA')),
    ("GP",_('GUADELOUPE')),
    ("GU",_('GUAM')),
    ("GT",_('GUATEMALA')),
    ("GG",_('GUERNSEY')),
    ("GN",_('GUINEA')),
    ("GW",_('GUINEA-BISSAU')),
    ("GY",_('GUYANA')),
    ("HT",_('HAITI')),
    ("HM",_('HEARD AND MCDONALD ISLANDS')),
    ("HN",_('HONDURAS')),
    ("HK",_('HONG KONG')),
    ("HU",_('HUNGARY')),
    ("IS",_('ICELAND')),
    ("IN",_('INDIA')),
    ("ID",_('INDONESIA')),
    ("IQ",_('IRAQ')),
    ("IE",_('IRELAND')),
    ("IM",_('ISLE OF MAN')),
    ("IL",_('ISRAEL')),
    ("IT",_('ITALY')),
    ("JM",_('JAMAICA')),
    ("JP",_('JAPAN')),
    ("JE",_('JERSEY')),
    ("JO",_('JORDAN')),
    ("KZ",_('KAZAKHSTAN')),
    ("KE",_('KENYA')),
    ("KI",_('KIRIBATI')),
    ("KW",_('KUWAIT')),
    ("KG",_('KYRGYZSTAN')),
    ("LA",_('LAOS')),
    ("LV",_('LATVIA')),
    ("LB",_('LEBANON')),
    ("LS",_('LESOTHO')),
    ("LR",_('LIBERIA')),
    ("LY",_('LIBYA')),
    ("LI",_('LICHTENSTEIN')),
    ("LT",_('LITHUANIA')),
    ("LU",_('LUXEMBOURG')),
    ("MO",_('MACAU')),
    ("MG",_('MADAGASCAR')),
    ("MW",_('MALAWI')),
    ("MY",_('MALAYSIA')),
    ("MV",_('MALDIVES')),
    ("ML",_('MALI')),
    ("MT",_('MALTA')),
    ("MH",_('MARSHALL ISLANDS')),
    ("MQ",_('MARTINIQUE')),
    ("MR",_('MAURITANIA')),
    ("MU",_('MAURITIUS')),
    ("YT",_('MAYOTTE')),
    ("MX",_('MEXICO')),
    ("FM",_('MICRONESIA')),
    ("MD",_('MOLDOVA')),
    ("MC",_('MONACO')),
    ("MN",_('MONGOLIA')),
    ("ME",_('MONTENEGRO')),
    ("MS",_('MONTSERRAT')),
    ("MA",_('MOROCCO')),
    ("MZ",_('MOZAMBIQUE')),
    ("NA",_('NAMIBIA')),
    ("NR",_('NAURU')),
    ("NP",_('NEPAL')),
    ("NL",_('NETHERLANDS')),
    ("AN",_('NETHERLANDS ANTILLES')),
    ("NC",_('NEW CALEDONIA')),
    ("NZ",_('NEW ZEALAND')),
    ("NI",_('NICARAGUA')),
    ("NE",_('NIGER')),
    ("NG",_('NIGERIA')),
    ("NU",_('NIUE')),
    ("NF",_('NORFOLK ISLAND')),
    ("MP",_('NORTHERN MARIANA ISLANDS')),
    ("NO",_('NORWAY')),
    ("OM",_('OMAN')),
    ("PK",_('PAKISTAN')),
    ("PW",_('PALAU')),
    ("PS",_('PALESTINIAN TERRITORIES')),
    ("PA",_('PANAMA')),
    ("PG",_('PAPUA NEW GUINEA')),
    ("PY",_('PARAGUAY')),
    ("PE",_('PERU')),
    ("PH",_('PHILIPPINES')),
    ("PN",_('PITCAIRN')),
    ("PL",_('POLAND')),
    ("PT",_('PORTUGAL')),
    ("PR",_('PUERTO RICO')),
    ("QA",_('QATAR')),
    ("RE",_('REUNION')),
    ("RO",_('ROMANIA')),
    ("RU",_('RUSSIAN FEDERATION')),
    ("RW",_('RWANDA')),
    ("BL",_('SAINT ')),
    ("KN",_('SAINT KITTS AND NEVIS')),
    ("LC",_('SAINT LUCIA')),
    ("MF",_('SAINT MARTIN')),
    ("VC",_('SAINT VINCENT AND THE GRENADINES')),
    ("WS",_('SAMOA')),
    ("SM",_('SAN MARINO')),
    ("ST",_('SAO TOME AND PRINCIPE')),
    ("SA",_('SAUDI ARABIA')),
    ("SN",_('SENEGAL')),
    ("RS",_('SERBIA')),
    ("SC",_('SEYCHELLES')),
    ("SL",_('SIERRA LEONE')),
    ("SG",_('SINGAPORE')),
    ("SX",_('SINT MAARTEN')),
    ("SK",_('SLOVAKIA (SLOVAK REPUBLIC)')),
    ("SI",_('SLOVENIA')),
    ("SB",_('SOLOMON ISLANDS')),
    ("SO",_('SOMALIA')),
    ("ZA",_('SOUTH AFRICA')),
    ("KR",_('SOUTH KOREA')),
    ("ES",_('SPAIN')),
    ("LK",_('SRI LANKA')),
    ("SH",_('ST. HELENA')),
    ("PM",_('ST. PIERRE AND MIQUELON')),
    ("SR",_('SURINAME')),
    ("SJ",_('SVALBARD AND JAN MAYEN ISLANDS')),
    ("SZ",_('SWAZILAND')),
    ("SE",_('SWEDEN')),
    ("CH",_('SWITZERLAND')),
    ("TW",_('TAIWAN')),
    ("TJ",_('TAJIKISTAN')),
    ("TZ",_('TANZANIA')),
    ("TH",_('THAILAND')),
    ("TL",_('TIMOR-LESTE')),
    ("TG",_('TOGO')),
    ("TK",_('TOKELAU')),
    ("TO",_('TONGA')),
    ("TT",_('TRINIDAD AND TOBAGO')),
    ("TN",_('TUNISIA')),
    ("TR",_('TURKEY')),
    ("TM",_('TURKMENISTAN')),
    ("TC",_('TURKS AND CAICOS ISLANDS')),
    ("TV",_('TUVALU')),
    ("UG",_('UGANDA')),
    ("UA",_('UKRAINE')),
    ("AE",_('UNITED ARAB EMIRATES')),
    ("GB",_('UNITED KINGDOM (GREAT BRITAIN)')),
    ("UM",_('UNITED STATES MINOR ISLANDS')),
    ("UY",_('URUGUAY')),
    ("UZ",_('UZBEKISTAN')),
    ("VU",_('VANUATU')),
    ("VA",_('VATICAN CITY')),
    ("VE",_('VENEZUELA')),
    ("VN",_('VIETNAM')),
    ("VG",_('VIRGIN ISLANDS (BRITISH)')),
    ("VI",_('VIRGIN ISLANDS (USA)')),
    ("WF",_('WALLIS AND FUTUNA')),
    ("EH",_('WESTERN SAHARA')),
    ("YE",_('YEMEN')),
    ("ZM",_('ZAMBIA')),
    ("ZW",_('ZIMBABWE')),
)